import csv
import pandas as pd 
import matplotlib.pyplot as plt 
import math 
'''
I/O Utility functions (vibe-coded). 
'''

def save_results_to_csv(simulator, filepath: str) -> None:
    """
    Save the time series results stored in a DynamicFBASimulator instance
    into a CSV file. The CSV will have a header with column names.
    """
    # Build header (first column is time, then biomass, then metabolites)
    fieldnames = ['time_s', 'biomass_gDW'] + list(simulator.ext_conc.keys())

    with open(filepath, mode='w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(fieldnames)

        # Number of time points
        n_steps = len(simulator.results['time_s'])

        for i in range(n_steps):
            row = [
                simulator.results['time_s'][i],
                simulator.results['biomass_gDW'][i],
                *[simulator.results[m][i] for m in simulator.ext_conc.keys()]
            ]
            writer.writerow(row)

    print(f"Results saved to {filepath}")

import pandas as pd
import matplotlib.pyplot as plt

def plot_results_from_csv(filepath: str, figsize=(10, 6)) -> None:
    """
    Load a CSV generated by save_results_to_csv() and plot:
        - Biomass over time
        - Each metabolite concentration over time
    """
    df = pd.read_csv(filepath)

    time = df['time_s'] / 3600.0
    biomass = df['biomass_gDW']

    # Start plot
    fig, ax = plt.subplots(figsize=figsize)

    # Plot biomass
    ax.plot(time, biomass, label='Biomass (gDW)', linewidth=2, linestyle='--', color='black', marker='^')

    # Plot metabolite concentrations
    for col in df.columns:
        if col not in ['time_s', 'biomass_gDW']:
            ax.plot(time, df[col], label=col, marker='o')

    ax.set_xlabel('Time (hr)')
    ax.set_ylabel('Concentration (mM) / Biomass (gDW)')
    ax.set_title('Dynamic FBA Simulation Results')
    ax.legend(loc='best', fontsize='small')
    plt.tight_layout()
    plt.show()

def plot_results_from_csv_separate(filepath: str, figsize=(10, 4)) -> None:
    """
    Load a CSV generated by save_results_to_csv() and create a separate
    subplot for biomass and each metabolite vs time.
    """
    df = pd.read_csv(filepath)

    time = df['time_s'] / 3600.0
    components = [col for col in df.columns if col != 'time_s']

    n_plots = len(components)
    ncols = 2  # You can change this to 1 or 3 based on preference
    nrows = math.ceil(n_plots / ncols)

    fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(figsize[0], figsize[1] * nrows))
    axes = axes.flatten()  # Flatten to make iterating easier

    for idx, comp in enumerate(components):
        axes[idx].plot(time, df[comp], label=comp, linewidth=2)
        axes[idx].set_title(comp)
        axes[idx].set_xlabel('Time (hr)')
        axes[idx].set_ylabel('Concentration (mM)' if comp != 'biomass_gDW' else 'Biomass (gDW)')
        axes[idx].grid(True)

    # Hide any unused subplots
    for ax in axes[len(components):]:
        ax.axis('off')

    plt.tight_layout()
    plt.show()
